variables:
  IMAGE_NAME: chrisdoherty4/docker:stabe-dind-executor

stages:
  - build
  
build:
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
