variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  
build:
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
